version: "3.7"

services: 
  database_query_challenge:
    image: postgres
    container_name: database_query_challenge
    restart: always
    ports:
      - 5432:5433
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database_query_challenge
    volumes: 
      - pgdata:/data/postgres

  app: 
    build: .
    container_name: desafio_queries_challenge
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database_query_challenge
    depends_on: 
      - database_query_challenge
volumes: 
  pgdata:
    driver: local
    